"""add_emotion_mapping_fields_v2

Revision ID: 357748608b36
Revises: f5b6fa371d99
Create Date: 2026-01-17 13:37:18.809409

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "357748608b36"
down_revision: Union[str, None] = "f5b6fa371d99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages",
        sa.Column("original_emotion_name", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "chat_messages", sa.Column("match_method", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "chat_messages", sa.Column("match_confidence", sa.Float(), nullable=True)
    )

    op.add_column(
        "detected_emotions",
        sa.Column("original_name", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "detected_emotions",
        sa.Column("match_method", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "detected_emotions", sa.Column("match_confidence", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("detected_emotions", "match_confidence")
    op.drop_column("detected_emotions", "match_method")
    op.drop_column("detected_emotions", "original_name")

    op.drop_column("chat_messages", "match_confidence")
    op.drop_column("chat_messages", "match_method")
    op.drop_column("chat_messages", "original_emotion_name")
    # ### end Alembic commands ###
