"""Initial schema with pgvector

Revision ID: 3d24332d682d
Revises:
Create Date: 2025-12-03 10:17:54.868299

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3d24332d682d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure pgvector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "atlas_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("emotion_name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("vac_vector", pgvector.sqlalchemy.Vector(dim=3), nullable=False),
        sa.Column("q_constant", pgvector.sqlalchemy.Vector(dim=4), nullable=False),
        sa.Column("semantic_embedding", pgvector.sqlalchemy.Vector(dim=384), nullable=False),
        sa.Column("haptic_pattern_id", sa.String(length=50), nullable=True),
        sa.Column("color_hint", sa.String(length=7), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_atlas_definitions_category"),
        "atlas_definitions",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_atlas_definitions_emotion_name"),
        "atlas_definitions",
        ["emotion_name"],
        unique=True,
    )
    op.create_table(
        "user_trajectory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_transcription", sa.Text(), nullable=True),
        sa.Column("input_embedding", pgvector.sqlalchemy.Vector(dim=384), nullable=True),
        sa.Column("vac_values", pgvector.sqlalchemy.Vector(dim=3), nullable=False),
        sa.Column("quaternion_state", pgvector.sqlalchemy.Vector(dim=4), nullable=False),
        sa.Column("dominant_emotion_id", sa.UUID(), nullable=True),
        sa.Column("elasticity_metric", sa.Float(), nullable=False),
        sa.Column("rigidity_score", sa.Float(), nullable=False),
        sa.Column("context_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["dominant_emotion_id"],
            ["atlas_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_trajectory_dominant_emotion_id"),
        "user_trajectory",
        ["dominant_emotion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_trajectory_session_id"),
        "user_trajectory",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_trajectory_timestamp"),
        "user_trajectory",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_trajectory_user_id"), "user_trajectory", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_trajectory_user_id"), table_name="user_trajectory")
    op.drop_index(op.f("ix_user_trajectory_timestamp"), table_name="user_trajectory")
    op.drop_index(op.f("ix_user_trajectory_session_id"), table_name="user_trajectory")
    op.drop_index(op.f("ix_user_trajectory_dominant_emotion_id"), table_name="user_trajectory")
    op.drop_table("user_trajectory")
    op.drop_index(op.f("ix_atlas_definitions_emotion_name"), table_name="atlas_definitions")
    op.drop_index(op.f("ix_atlas_definitions_category"), table_name="atlas_definitions")
    op.drop_table("atlas_definitions")
    # ### end Alembic commands ###
