"""add_users_table_and_auth_fields

Revision ID: 61c715628382
Revises: bf7g8h9i0j1k
Create Date: 2026-01-07 16:57:10.514204

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "61c715628382"
down_revision: Union[str, None] = "bf7g8h9i0j1k"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    # 1. Create users table if not exists
    if "users" not in tables:
        op.create_table(
            "users",
            sa.Column(
                "id",
                sa.Uuid(),
                server_default=sa.text("gen_random_uuid()"),
                nullable=False,
            ),
            sa.Column("email", sa.String(length=255), nullable=False),
            sa.Column("password_hash", sa.String(length=255), nullable=False),
            sa.Column("full_name", sa.String(length=255), nullable=True),
            sa.Column("role", sa.String(length=50), nullable=False),
            sa.Column(
                "is_active",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("true"),
            ),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        # Indexes for users
        op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    # 2. Add auth_user_id to chat_sessions if not exists
    if "chat_sessions" in tables:
        columns = [c["name"] for c in inspector.get_columns("chat_sessions")]
        if "auth_user_id" not in columns:
            op.add_column(
                "chat_sessions", sa.Column("auth_user_id", sa.Uuid(), nullable=True)
            )
            op.create_index(
                op.f("ix_chat_sessions_auth_user_id"),
                "chat_sessions",
                ["auth_user_id"],
                unique=False,
            )
            op.create_foreign_key(
                None, "chat_sessions", "users", ["auth_user_id"], ["id"]
            )


def downgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    if "chat_sessions" in tables:
        columns = [c["name"] for c in inspector.get_columns("chat_sessions")]
        if "auth_user_id" in columns:
            # check constraint name? tough to know autogenerated name.
            # op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
            # might fail if we don't know name. ignoring for now or handle gracefully?
            try:
                op.drop_constraint(
                    "chat_sessions_auth_user_id_fkey",
                    "chat_sessions",
                    type_="foreignkey",
                )
            except:
                pass
            op.drop_index(
                op.f("ix_chat_sessions_auth_user_id"), table_name="chat_sessions"
            )
            op.drop_column("chat_sessions", "auth_user_id")

    if "users" in tables:
        op.drop_index(op.f("ix_users_email"), table_name="users")
        op.drop_table("users")
