---
- name: Determine if love-secrets exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: love-secrets
    namespace: "{{ project_name }}"
  register: existing_secrets

- name: Set facts from existing existing_secrets
  set_fact:
    db_password_b64: "{{ existing_secrets.resources[0].data.DB_PASSWORD }}"
  when: existing_secrets.resources | length > 0 and 'DB_PASSWORD' in existing_secrets.resources[0].data

- name: Generate new random DB password if needed
  set_fact:
    db_password_b64: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') | b64encode }}"
  when: db_password_b64 is not defined

- name: Ensure love-secrets exists with DB password
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: love-secrets
        namespace: "{{ project_name }}"
      type: Opaque
      data:
        DB_PASSWORD: "{{ db_password_b64 }}"

- name: Ensure love-config ConfigMap exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: love-config
        namespace: "{{ project_name }}"
      data:
        DB_NAME: "{{ db_name }}"
        DB_USER: "{{ db_user }}"
