---
- name: Determine if love-secrets exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: love-secrets
    namespace: "{{ project_name }}"
  register: existing_secrets

- name: Set facts from existing existing_secrets
  set_fact:
    db_password_b64: "{{ existing_secrets.resources[0].data.DB_PASSWORD }}"
    secret_key_b64: "{{ existing_secrets.resources[0].data.SECRET_KEY | default('') }}"
  when: existing_secrets.resources | length > 0 and 'DB_PASSWORD' in existing_secrets.resources[0].data

- name: Generate new random DB password if needed
  set_fact:
    db_password_b64: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') | b64encode }}"
  when: db_password_b64 is not defined

- name: Generate new random SECRET_KEY if needed
  set_fact:
    secret_key_b64: "{{ lookup('password', '/dev/null length=48 chars=ascii_letters,digits') | b64encode }}"
  when: secret_key_b64 is not defined or secret_key_b64 == ''

- name: Ensure love-secrets exists with DB password and SECRET_KEY
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: love-secrets
        namespace: "{{ project_name }}"
      type: Opaque
      data:
        DB_PASSWORD: "{{ db_password_b64 }}"
        SECRET_KEY: "{{ secret_key_b64 }}"

- name: Ensure love-config ConfigMap exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: love-config
        namespace: "{{ project_name }}"
      data:
        DB_NAME: "{{ db_name }}"
        DB_USER: "{{ db_user }}"
        ALLOWED_ORIGINS: '["http://localhost:3000", "http://127.0.0.1:3000", "http://localhost:19006", "https://love-experience-love-stack.apps-crc.testing"]'
