---
- name: Install Redis
  dnf:
    name: redis
    state: present

- name: Configure Redis to bind to localhost
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind '
    line: 'bind 127.0.0.1'
    state: present
  notify: Restart Redis

- name: Enable and Start Redis
  service:
    name: redis
    state: started
    enabled: yes
