import MetalKit
import SoulCore

// MARK: - Pipeline Configuration
extension SoulRenderer {
    
    internal func buildPipeline() {
        // Robust Library Loading
        var library: MTLLibrary?
        
        print("🔍 Debugging Metal Library Loading...")
        print("📂 Bundle.main path: \(Bundle.main.bundlePath)")
        // Accessing Bundle.module might crash if not found, so we wrap in a standalone check if possible, 
        // but Bundle.module is a static computed property.
        
        // Strategy 1: Automatic Bundle.module with Named Library
        // We prioritize "SoulUI.metallib" generated by the plugin to avoid collision with Xcode's default.metallib
        do {
            let bundle = Bundle.module
            print("📦 Bundle.module path: \(bundle.bundlePath)")
            
            // Try loading specific plugin artifact
            if let libURL = bundle.url(forResource: "SoulUI", withExtension: "metallib") {
                library = try device.makeLibrary(URL: libURL)
                print("✅ Found SoulUI.metallib at \(libURL.lastPathComponent)")
            } else {
                // Fallback to default
                library = try device.makeDefaultLibrary(bundle: bundle)
                print("✅ Found default.metallib in Bundle.module")
            }
        } catch {
            print("⚠️ Bundle.module load failed: \(error)")
        }

        // Strategy 2: Explicit Search for SoulUI_SoulUI.bundle
        if library == nil {
             if let bundleURL = Bundle.main.url(forResource: "SoulUI_SoulUI", withExtension: "bundle"),
                let bundle = Bundle(url: bundleURL) {
                 print("📦 Found explicit SoulUI_SoulUI.bundle at \(bundleURL)")
                 library = try? device.makeDefaultLibrary(bundle: bundle)
                 if library != nil { print("✅ Loaded from explicit SoulUI bundle") }
             }
        }
        
        // Strategy 3: Bundle.main Fallback
        if library == nil {
            print("⚠️ Trying Bundle.main...")
            library = try? device.makeDefaultLibrary(bundle: Bundle.main)
        }
        
        // Strategy 4: Device Default
        if library == nil {
            print("⚠️ Trying System Default...")
            library = device.makeDefaultLibrary()
        }
        
        guard let library = library else {
            print("❌ ABSOLUTE FAILURE: Could not load Metal library in any way.")
            return
        }
        
        // List Functions
        print("📚 Available functions: \(library.functionNames)")
        
        // 0. Depth State
        print("⚙️ creating Depth State...")
        let depthDesc = MTLDepthStencilDescriptor()
        depthDesc.depthCompareFunction = .less
        depthDesc.isDepthWriteEnabled = false 
        self.depthState = device.makeDepthStencilState(descriptor: depthDesc)
        print("✅ Depth State created")
        
        // 1. Background Liquid Sphere Pipeline
        print("⚙️ configuring Liquid Pipeline...")
        let descriptor = MTLRenderPipelineDescriptor()
        descriptor.label = "Soul Shader Pipeline"
        
        guard let vertFunc = library.makeFunction(name: "vertexPassthrough") else {
             print("❌ Failed to find vertexPassthrough")
             return
        }
        guard let fragFunc = library.makeFunction(name: "liquidSoul") else {
             print("❌ Failed to find liquidSoul")
             return
        }
        descriptor.vertexFunction = vertFunc
        descriptor.fragmentFunction = fragFunc
        descriptor.colorAttachments[0].pixelFormat = .bgra8Unorm
        descriptor.depthAttachmentPixelFormat = .depth32Float
        
        descriptor.colorAttachments[0].isBlendingEnabled = true
        descriptor.colorAttachments[0].sourceRGBBlendFactor = .sourceAlpha
        descriptor.colorAttachments[0].destinationRGBBlendFactor = .oneMinusSourceAlpha
        
        do {
            print("⚙️ compiling Liquid Pipeline State...")
            pipelineState = try device.makeRenderPipelineState(descriptor: descriptor)
            print("✅ Liquid Pipeline created")
        } catch {
            print("❌ Failed to create pipeline state: \(error)")
        }
        
        // 2. Point Cloud Pipeline
        print("⚙️ configuring Point Pipeline...")
        let pointDesc = MTLRenderPipelineDescriptor()
        pointDesc.label = "Point Cloud Pipeline"
        pointDesc.vertexFunction = library.makeFunction(name: "vertexPoint")
        pointDesc.fragmentFunction = library.makeFunction(name: "fragmentPoint")
        pointDesc.colorAttachments[0].pixelFormat = .bgra8Unorm
        pointDesc.depthAttachmentPixelFormat = .depth32Float
        
        pointDesc.colorAttachments[0].isBlendingEnabled = true
        pointDesc.colorAttachments[0].sourceRGBBlendFactor = .sourceAlpha
        pointDesc.colorAttachments[0].destinationRGBBlendFactor = .one 
        
        do {
            print("⚙️ compiling Point Pipeline State...")
            pointPipeline = try device.makeRenderPipelineState(descriptor: pointDesc)
             print("✅ Point Pipeline created")
        } catch {
             print("❌ Failed to create point pipeline: \(error)")
        }
        
        // 3. Path Pipeline (Lines)
        print("⚙️ configuring Path Pipeline...")
        let pathDesc = MTLRenderPipelineDescriptor()
        pathDesc.label = "Path Pipeline"
        pathDesc.vertexFunction = library.makeFunction(name: "vertexLine")
        pathDesc.fragmentFunction = library.makeFunction(name: "fragmentLine")
        pathDesc.colorAttachments[0].pixelFormat = .bgra8Unorm
        pathDesc.depthAttachmentPixelFormat = .depth32Float
        
        pathDesc.colorAttachments[0].isBlendingEnabled = true
        pathDesc.colorAttachments[0].sourceRGBBlendFactor = .sourceAlpha
        pathDesc.colorAttachments[0].destinationRGBBlendFactor = .one
        
        do {
            print("⚙️ compiling Path Pipeline State...")
            pathPipeline = try device.makeRenderPipelineState(descriptor: pathDesc)
             print("✅ Path Pipeline created")
        } catch {
             print("❌ Failed to create path pipeline: \(error)")
        }
        
        print("🏁 buildPipeline completed")
    }
}
