"""multi_emotion_collections

Revision ID: 0e896f34fb2e
Revises: 870b1a357de9
Create Date: 2026-01-20 14:46:04.119293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e896f34fb2e'
down_revision: Union[str, None] = '870b1a357de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_collections_name'), 'emotion_collections', ['name'], unique=True)
    
    # 1. Rename table instead of creating new one
    op.rename_table('atlas_definitions', 'emotion_definitions')

    # 2. Add collection_id column (nullable first)
    op.add_column('emotion_definitions', sa.Column('collection_id', sa.Uuid(), nullable=True))

    # 3. Data Migration: Create default collection and link existing emotions
    op.execute("INSERT INTO emotion_collections (id, name, is_default, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Atlas of the Heart', true, true, now(), now())")
    op.execute("UPDATE emotion_definitions SET collection_id = (SELECT id FROM emotion_collections WHERE name = 'Atlas of the Heart' LIMIT 1)")

    # 4. Enforce constraints
    op.alter_column('emotion_definitions', 'collection_id', nullable=False)
    op.create_foreign_key(None, 'emotion_definitions', 'emotion_collections', ['collection_id'], ['id'])
    
    # 5. Update Indices and Constraints
    # Drop old uniqueness (was on emotion_name)
    # Note: Using 'emotion_definitions' as table name since it was renamed
    
    # Create new composite unique constraint
    op.create_unique_constraint('uq_collection_emotion_name', 'emotion_definitions', ['collection_id', 'emotion_name'])

    # Handle Rename/Recreate of Indices
    op.drop_index('ix_atlas_definitions_category', table_name='emotion_definitions')
    op.drop_index('ix_atlas_definitions_emotion_name', table_name='emotion_definitions')
    
    op.create_index(op.f('ix_emotion_definitions_category'), 'emotion_definitions', ['category'], unique=False)
    op.create_index(op.f('ix_emotion_definitions_emotion_name'), 'emotion_definitions', ['emotion_name'], unique=False)
    op.create_index(op.f('ix_emotion_definitions_collection_id'), 'emotion_definitions', ['collection_id'], unique=False)
    op.alter_column('category_transitions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('category_transitions', 'difficulty_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Scale 0-1 where 1.0 = impossible without bridge',
               existing_nullable=False)
    op.alter_column('category_transitions', 'is_prohibited',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('category_transitions', 'requires_bridge',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('category_transitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('category_transitions_from_category_to_category_key', 'category_transitions', type_='unique')
    op.drop_index('idx_category_trans_difficulty', table_name='category_transitions')
    op.drop_index('idx_category_trans_from', table_name='category_transitions')
    op.drop_index('idx_category_trans_to', table_name='category_transitions')
    op.drop_table_comment(
        'category_transitions',
        existing_comment='Difficulty matrix for category-to-category emotional transitions',
        schema=None
    )
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_messages', 'prosody_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSONB storage for detailed voice features (jitter, shimmer, HNR, etc.)',
               existing_nullable=True)
    op.alter_column('chat_messages', 'insights',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='AI-generated insights combining voice and content analysis',
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_chat_messages_emotion_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_timestamp', table_name='chat_messages')
    op.drop_index('ix_chat_messages_semantic_embedding', table_name='chat_messages', postgresql_ops={'semantic_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_chat_messages_emotion_id'), 'chat_messages', ['emotion_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_timestamp'), 'chat_messages', ['timestamp'], unique=False)
    op.drop_constraint('chat_messages_emotion_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'emotion_definitions', ['emotion_id'], ['id'])
    op.drop_table_comment(
        'chat_messages',
        existing_comment='Individual messages within chat sessions with analysis data',
        schema=None
    )
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_sessions', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('chat_sessions', 'tone_preference',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.alter_column('chat_sessions', 'deep_feeling_mode',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_chat_sessions_started_at', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_started_at'), 'chat_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_table_comment(
        'chat_sessions',
        existing_comment='Chat sessions for emotional analysis chat interface',
        schema=None
    )
    op.alter_column('clinical_alerts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'level',
               existing_type=postgresql.ENUM('critical', 'warning', 'attention', 'stable', name='alert_level'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'type',
               existing_type=postgresql.ENUM('high_arousal', 'voice_mismatch', 'low_confidence', 'pattern_concern', 'voice_quality', name='alert_type'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'suggestion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('clinical_alerts', 'triggered_by',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='VAC and prosody values that triggered the alert',
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'threshold_used',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Clinical thresholds applied for this alert evaluation',
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'version',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment=None,
               existing_comment='Alert rule version for tracking threshold changes over time',
               existing_nullable=False)
    op.drop_index('idx_clinical_alerts_level', table_name='clinical_alerts')
    op.drop_index('idx_clinical_alerts_session', table_name='clinical_alerts')
    op.drop_index('idx_clinical_alerts_timestamp', table_name='clinical_alerts')
    op.drop_index('idx_clinical_alerts_type', table_name='clinical_alerts')
    op.create_index(op.f('ix_clinical_alerts_level'), 'clinical_alerts', ['level'], unique=False)
    op.create_index(op.f('ix_clinical_alerts_session_id'), 'clinical_alerts', ['session_id'], unique=False)
    op.create_index(op.f('ix_clinical_alerts_timestamp'), 'clinical_alerts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_clinical_alerts_type'), 'clinical_alerts', ['type'], unique=False)
    op.drop_constraint('clinical_alerts_session_id_fkey', 'clinical_alerts', type_='foreignkey')
    op.create_foreign_key(None, 'clinical_alerts', 'chat_sessions', ['session_id'], ['id'])
    op.drop_table_comment(
        'clinical_alerts',
        existing_comment='Stores clinical alert evaluations for emotional analysis sessions with audit trail',
        schema=None
    )
    op.drop_column('clinical_alerts', 'created_at')
    op.alter_column('detected_emotions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('detected_emotions', 'emotion_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Foreign key with CASCADE to allow atlas re-seeding',
               existing_nullable=True)
    op.alter_column('detected_emotions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_detected_emotions_analysis', table_name='detected_emotions')
    op.drop_index('idx_detected_emotions_emotion', table_name='detected_emotions')
    op.drop_index('idx_detected_emotions_prominence', table_name='detected_emotions')
    op.create_index(op.f('ix_detected_emotions_analysis_id'), 'detected_emotions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_detected_emotions_emotion_id'), 'detected_emotions', ['emotion_id'], unique=False)
    op.create_index(op.f('ix_detected_emotions_prominence'), 'detected_emotions', ['prominence'], unique=False)
    op.drop_constraint('detected_emotions_emotion_id_fkey', 'detected_emotions', type_='foreignkey')
    op.create_foreign_key(None, 'detected_emotions', 'emotion_definitions', ['emotion_id'], ['id'])
    op.drop_table_comment(
        'detected_emotions',
        existing_comment='Individual emotions (1-3) detected in multi-emotion analysis',
        schema=None
    )
    op.alter_column('emotion_goals', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('emotion_goals', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('emotion_goals', 'target_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('emotion_goals', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('emotion_goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('emotion_goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_emotion_goals_session', table_name='emotion_goals')
    op.drop_index('idx_emotion_goals_status', table_name='emotion_goals')
    op.drop_index('idx_emotion_goals_user', table_name='emotion_goals')
    op.create_index(op.f('ix_emotion_goals_session_id'), 'emotion_goals', ['session_id'], unique=False)
    op.create_index(op.f('ix_emotion_goals_status'), 'emotion_goals', ['status'], unique=False)
    op.create_index(op.f('ix_emotion_goals_user_id'), 'emotion_goals', ['user_id'], unique=False)
    op.drop_constraint('emotion_goals_goal_emotion_id_fkey', 'emotion_goals', type_='foreignkey')
    op.create_foreign_key(None, 'emotion_goals', 'emotion_definitions', ['goal_emotion_id'], ['id'])
    op.drop_table_comment(
        'emotion_goals',
        existing_comment='User-defined emotion goals for transition pathfinding',
        schema=None
    )
    op.alter_column('emotion_relationships', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('emotion_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_emotion_rel_analysis', table_name='emotion_relationships')
    op.drop_index('idx_emotion_rel_type', table_name='emotion_relationships')
    op.create_index(op.f('ix_emotion_relationships_analysis_id'), 'emotion_relationships', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_emotion_relationships_relationship_type'), 'emotion_relationships', ['relationship_type'], unique=False)
    op.drop_table_comment(
        'emotion_relationships',
        existing_comment='Pairwise relationships: complementary, contradictory, masking, etc.',
        schema=None
    )
    op.alter_column('journey_waypoints', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('journey_waypoints', 'reasoning',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Psychological explanation for why this waypoint is chosen',
               existing_nullable=True)
    op.alter_column('journey_waypoints', 'reached',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('journey_waypoints', 'reached_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('journey_waypoints', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_waypoints_journey', table_name='journey_waypoints')
    op.drop_index('idx_waypoints_journey_order', table_name='journey_waypoints')
    op.drop_index('idx_waypoints_reached', table_name='journey_waypoints')
    op.drop_constraint('journey_waypoints_journey_id_waypoint_index_key', 'journey_waypoints', type_='unique')
    op.drop_constraint('journey_waypoints_emotion_id_fkey', 'journey_waypoints', type_='foreignkey')
    op.drop_constraint('journey_waypoints_journey_id_fkey', 'journey_waypoints', type_='foreignkey')
    op.drop_table_comment(
        'journey_waypoints',
        existing_comment='Individual waypoints within a journey with progress tracking',
        schema=None
    )
    op.alter_column('model_assignments', 'function',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='AI function name (semantic_vac, multi_emotion, insight_generation, atlas_mapping)',
               existing_nullable=False)
    op.alter_column('model_assignments', 'ai_model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Ollama model name (e.g., llama3.1:8b-instruct-q4_0)',
               existing_nullable=False)
    op.alter_column('model_assignments', 'avg_latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Exponential moving average of latency in milliseconds',
               existing_nullable=True)
    op.alter_column('model_assignments', 'total_invocations',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='Total number of times this model has been used for this function',
               existing_nullable=False)
    op.drop_index('idx_model_assignments_model_name', table_name='model_assignments')
    op.drop_table_comment(
        'model_assignments',
        existing_comment='Stores which Ollama model is assigned to each AI function',
        schema=None
    )
    op.alter_column('multi_emotion_analyses', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('multi_emotion_analyses', 'deep_feeling_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('multi_emotion_analyses', 'three_way_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('multi_emotion_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_multi_emotion_created', table_name='multi_emotion_analyses')
    op.drop_index('idx_multi_emotion_message', table_name='multi_emotion_analyses')
    op.drop_index('idx_multi_emotion_session', table_name='multi_emotion_analyses')
    op.drop_index('idx_multi_emotion_three_way', table_name='multi_emotion_analyses')
    op.create_index(op.f('ix_multi_emotion_analyses_created_at'), 'multi_emotion_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_multi_emotion_analyses_message_id'), 'multi_emotion_analyses', ['message_id'], unique=False)
    op.create_index(op.f('ix_multi_emotion_analyses_session_id'), 'multi_emotion_analyses', ['session_id'], unique=False)
    op.create_index(op.f('ix_multi_emotion_analyses_three_way_enabled'), 'multi_emotion_analyses', ['three_way_enabled'], unique=False)
    op.drop_table_comment(
        'multi_emotion_analyses',
        existing_comment='Deep Feeling Mode: Multi-emotion analysis with complexity metrics',
        schema=None
    )
    op.alter_column('pattern_strategies', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pattern_strategies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_pattern_strategies_order', table_name='pattern_strategies')
    op.drop_index('idx_pattern_strategies_pattern', table_name='pattern_strategies')
    op.drop_constraint('pattern_strategies_pattern_id_strategy_id_key', 'pattern_strategies', type_='unique')
    op.drop_constraint('pattern_strategies_pattern_id_fkey', 'pattern_strategies', type_='foreignkey')
    op.drop_constraint('pattern_strategies_strategy_id_fkey', 'pattern_strategies', type_='foreignkey')
    op.drop_table_comment(
        'pattern_strategies',
        existing_comment='Junction table mapping strategies to patterns',
        schema=None
    )
    op.alter_column('session_analytics', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('session_analytics', 'emotion_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('session_analytics', 'average_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('session_analytics', 'total_duration_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('session_analytics', 'critical_alert_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('session_analytics', 'warning_alert_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('session_analytics', 'attention_alert_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('session_analytics', 'category_counts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='Breakdown of emotions by category: {"anxiety": 3, "joy": 2, ...}',
               existing_nullable=False)
    op.alter_column('session_analytics', 'vac_stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment=None,
               existing_comment='Aggregated VAC statistics: {valence_avg, arousal_avg, connection_avg, ...}',
               existing_nullable=False)
    op.drop_index('idx_session_analytics_dominant_category', table_name='session_analytics')
    op.drop_index('idx_session_analytics_emotion_count', table_name='session_analytics')
    op.drop_index('idx_session_analytics_session', table_name='session_analytics')
    op.drop_index('idx_session_analytics_start_time', table_name='session_analytics')
    op.drop_constraint('session_analytics_session_id_key', 'session_analytics', type_='unique')
    op.create_index(op.f('ix_session_analytics_session_id'), 'session_analytics', ['session_id'], unique=True)
    op.drop_constraint('session_analytics_session_id_fkey', 'session_analytics', type_='foreignkey')
    op.create_foreign_key(None, 'session_analytics', 'chat_sessions', ['session_id'], ['id'])
    op.drop_table_comment(
        'session_analytics',
        existing_comment='Real-time aggregated metrics for emotional analysis sessions',
        schema=None
    )
    op.alter_column('strategy_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('strategy_attempts', 'tried',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('strategy_attempts', 'tried_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategy_attempts', 'time_spent',
               existing_type=postgresql.INTERVAL(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('strategy_attempts', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('strategy_attempts', 'abandoned',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('strategy_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_attempts_helpful', table_name='strategy_attempts')
    op.drop_index('idx_attempts_journey', table_name='strategy_attempts')
    op.drop_index('idx_attempts_strategy', table_name='strategy_attempts')
    op.drop_index('idx_attempts_strategy_rating', table_name='strategy_attempts')
    op.drop_constraint('strategy_attempts_strategy_id_fkey', 'strategy_attempts', type_='foreignkey')
    op.drop_constraint('strategy_attempts_journey_id_fkey', 'strategy_attempts', type_='foreignkey')
    op.drop_table_comment(
        'strategy_attempts',
        existing_comment='Records of strategy usage and user-reported effectiveness',
        schema=None
    )
    op.alter_column('transition_patterns', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transition_patterns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_pattern_categories', table_name='transition_patterns')
    op.drop_table_comment(
        'transition_patterns',
        existing_comment='Common emotional transition patterns (e.g., high arousal to low arousal)',
        schema=None
    )
    op.alter_column('transition_strategies', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transition_strategies', 'strategy_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Based on Gross (1998) Process Model of Emotion Regulation',
               existing_nullable=False)
    op.alter_column('transition_strategies', 'evidence_level',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Hierarchy: meta_analysis > rct > clinical > theoretical',
               existing_nullable=False)
    op.alter_column('transition_strategies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transition_strategies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_strategy_difficulty', table_name='transition_strategies')
    op.drop_index('idx_strategy_evidence', table_name='transition_strategies')
    op.drop_index('idx_strategy_type', table_name='transition_strategies')
    op.drop_table_comment(
        'transition_strategies',
        existing_comment='Evidence-based emotion regulation strategies from research literature',
        schema=None
    )
    op.alter_column('user_journeys', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_journeys', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_journeys', 'current_waypoint',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)




    op.alter_column('user_journeys', 'context_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Contextual factors: location, time, support, energy level',
               existing_nullable=True)


    op.drop_index('idx_user_journeys_started', table_name='user_journeys')
    op.drop_index('idx_user_journeys_status', table_name='user_journeys')
    op.drop_index('idx_user_journeys_user_id', table_name='user_journeys')
    op.drop_index('idx_user_journeys_user_status', table_name='user_journeys')
    op.drop_constraint('user_journeys_goal_emotion_id_fkey', 'user_journeys', type_='foreignkey')
    op.drop_constraint('user_journeys_start_emotion_id_fkey', 'user_journeys', type_='foreignkey')
    op.drop_table_comment(
        'user_journeys',
        existing_comment='User emotional transition attempts and progress tracking',
        schema=None
    )
    op.alter_column('user_trajectory', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint('user_trajectory_dominant_emotion_id_fkey', 'user_trajectory', type_='foreignkey')
    op.create_foreign_key(None, 'user_trajectory', 'emotion_definitions', ['dominant_emotion_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'user_trajectory', type_='foreignkey')
    op.create_foreign_key('user_trajectory_dominant_emotion_id_fkey', 'user_trajectory', 'atlas_definitions', ['dominant_emotion_id'], ['id'])
    op.alter_column('user_trajectory', 'timestamp',
               existing_type=sa.DateTime(),
               server_default=None,
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_table_comment(
        'user_journeys',
        'User emotional transition attempts and progress tracking',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('user_journeys_start_emotion_id_fkey', 'user_journeys', 'atlas_definitions', ['start_emotion_id'], ['id'])
    op.create_foreign_key('user_journeys_goal_emotion_id_fkey', 'user_journeys', 'atlas_definitions', ['goal_emotion_id'], ['id'])
    op.create_index('idx_user_journeys_user_status', 'user_journeys', ['user_id', 'status'], unique=False)
    op.create_index('idx_user_journeys_user_id', 'user_journeys', ['user_id'], unique=False)
    op.create_index('idx_user_journeys_status', 'user_journeys', ['status'], unique=False)
    op.create_index('idx_user_journeys_started', 'user_journeys', ['started_at'], unique=False)
    op.alter_column('user_journeys', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_journeys', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_journeys', 'context_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Contextual factors: location, time, support, energy level',
               existing_nullable=True)
    op.alter_column('user_journeys', 'paused_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('user_journeys', 'abandoned_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('user_journeys', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('user_journeys', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_journeys', 'current_waypoint',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('user_journeys', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'in_progress'::character varying"),
               existing_nullable=False)
    op.alter_column('user_journeys', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'transition_strategies',
        'Evidence-based emotion regulation strategies from research literature',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_strategy_type', 'transition_strategies', ['strategy_type'], unique=False)
    op.create_index('idx_strategy_evidence', 'transition_strategies', ['evidence_level'], unique=False)
    op.create_index('idx_strategy_difficulty', 'transition_strategies', ['difficulty_level'], unique=False)
    op.alter_column('transition_strategies', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transition_strategies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transition_strategies', 'evidence_level',
               existing_type=sa.VARCHAR(length=50),
               comment='Hierarchy: meta_analysis > rct > clinical > theoretical',
               existing_nullable=False)
    op.alter_column('transition_strategies', 'strategy_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Based on Gross (1998) Process Model of Emotion Regulation',
               existing_nullable=False)
    op.alter_column('transition_strategies', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'transition_patterns',
        'Common emotional transition patterns (e.g., high arousal to low arousal)',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_pattern_categories', 'transition_patterns', ['from_category', 'to_category'], unique=False)
    op.alter_column('transition_patterns', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transition_patterns', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'strategy_attempts',
        'Records of strategy usage and user-reported effectiveness',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('strategy_attempts_journey_id_fkey', 'strategy_attempts', 'user_journeys', ['journey_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('strategy_attempts_strategy_id_fkey', 'strategy_attempts', 'transition_strategies', ['strategy_id'], ['id'])
    op.create_index('idx_attempts_strategy_rating', 'strategy_attempts', ['strategy_id', 'helpful_rating'], unique=False)
    op.create_index('idx_attempts_strategy', 'strategy_attempts', ['strategy_id'], unique=False)
    op.create_index('idx_attempts_journey', 'strategy_attempts', ['journey_id'], unique=False)
    op.create_index('idx_attempts_helpful', 'strategy_attempts', ['helpful_rating'], unique=False)
    op.alter_column('strategy_attempts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategy_attempts', 'abandoned',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('strategy_attempts', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('strategy_attempts', 'time_spent',
               existing_type=sa.String(length=50),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)
    op.alter_column('strategy_attempts', 'tried_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategy_attempts', 'tried',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('strategy_attempts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'session_analytics',
        'Real-time aggregated metrics for emotional analysis sessions',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'session_analytics', type_='foreignkey')
    op.create_foreign_key('session_analytics_session_id_fkey', 'session_analytics', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_session_analytics_session_id'), table_name='session_analytics')
    op.create_unique_constraint('session_analytics_session_id_key', 'session_analytics', ['session_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_session_analytics_start_time', 'session_analytics', ['start_time'], unique=False)
    op.create_index('idx_session_analytics_session', 'session_analytics', ['session_id'], unique=True)
    op.create_index('idx_session_analytics_emotion_count', 'session_analytics', ['emotion_count'], unique=False)
    op.create_index('idx_session_analytics_dominant_category', 'session_analytics', ['dominant_category'], unique=False)
    op.alter_column('session_analytics', 'vac_stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='Aggregated VAC statistics: {valence_avg, arousal_avg, connection_avg, ...}',
               existing_nullable=False)
    op.alter_column('session_analytics', 'category_counts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment='Breakdown of emotions by category: {"anxiety": 3, "joy": 2, ...}',
               existing_nullable=False)
    op.alter_column('session_analytics', 'attention_alert_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('session_analytics', 'warning_alert_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('session_analytics', 'critical_alert_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('session_analytics', 'total_duration_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('session_analytics', 'average_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('session_analytics', 'emotion_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('session_analytics', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'pattern_strategies',
        'Junction table mapping strategies to patterns',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('pattern_strategies_strategy_id_fkey', 'pattern_strategies', 'transition_strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('pattern_strategies_pattern_id_fkey', 'pattern_strategies', 'transition_patterns', ['pattern_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('pattern_strategies_pattern_id_strategy_id_key', 'pattern_strategies', ['pattern_id', 'strategy_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_pattern_strategies_pattern', 'pattern_strategies', ['pattern_id'], unique=False)
    op.create_index('idx_pattern_strategies_order', 'pattern_strategies', ['pattern_id', 'recommendation_order'], unique=False)
    op.alter_column('pattern_strategies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pattern_strategies', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'multi_emotion_analyses',
        'Deep Feeling Mode: Multi-emotion analysis with complexity metrics',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_multi_emotion_analyses_three_way_enabled'), table_name='multi_emotion_analyses')
    op.drop_index(op.f('ix_multi_emotion_analyses_session_id'), table_name='multi_emotion_analyses')
    op.drop_index(op.f('ix_multi_emotion_analyses_message_id'), table_name='multi_emotion_analyses')
    op.drop_index(op.f('ix_multi_emotion_analyses_created_at'), table_name='multi_emotion_analyses')
    op.create_index('idx_multi_emotion_three_way', 'multi_emotion_analyses', ['three_way_enabled'], unique=False)
    op.create_index('idx_multi_emotion_session', 'multi_emotion_analyses', ['session_id'], unique=False)
    op.create_index('idx_multi_emotion_message', 'multi_emotion_analyses', ['message_id'], unique=False)
    op.create_index('idx_multi_emotion_created', 'multi_emotion_analyses', ['created_at'], unique=False)
    op.alter_column('multi_emotion_analyses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('multi_emotion_analyses', 'three_way_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('multi_emotion_analyses', 'deep_feeling_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('multi_emotion_analyses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'model_assignments',
        'Stores which Ollama model is assigned to each AI function',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_model_assignments_model_name', 'model_assignments', ['ai_model_name'], unique=False)
    op.alter_column('model_assignments', 'total_invocations',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='Total number of times this model has been used for this function',
               existing_nullable=False)
    op.alter_column('model_assignments', 'avg_latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Exponential moving average of latency in milliseconds',
               existing_nullable=True)
    op.alter_column('model_assignments', 'ai_model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Ollama model name (e.g., llama3.1:8b-instruct-q4_0)',
               existing_nullable=False)
    op.alter_column('model_assignments', 'function',
               existing_type=sa.VARCHAR(length=50),
               comment='AI function name (semantic_vac, multi_emotion, insight_generation, atlas_mapping)',
               existing_nullable=False)
    op.create_table_comment(
        'journey_waypoints',
        'Individual waypoints within a journey with progress tracking',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('journey_waypoints_journey_id_fkey', 'journey_waypoints', 'user_journeys', ['journey_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('journey_waypoints_emotion_id_fkey', 'journey_waypoints', 'atlas_definitions', ['emotion_id'], ['id'])
    op.create_unique_constraint('journey_waypoints_journey_id_waypoint_index_key', 'journey_waypoints', ['journey_id', 'waypoint_index'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_waypoints_reached', 'journey_waypoints', ['reached'], unique=False)
    op.create_index('idx_waypoints_journey_order', 'journey_waypoints', ['journey_id', 'waypoint_index'], unique=False)
    op.create_index('idx_waypoints_journey', 'journey_waypoints', ['journey_id'], unique=False)
    op.alter_column('journey_waypoints', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('journey_waypoints', 'reached_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('journey_waypoints', 'reached',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('journey_waypoints', 'reasoning',
               existing_type=sa.TEXT(),
               comment='Psychological explanation for why this waypoint is chosen',
               existing_nullable=True)
    op.alter_column('journey_waypoints', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'emotion_relationships',
        'Pairwise relationships: complementary, contradictory, masking, etc.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_emotion_relationships_relationship_type'), table_name='emotion_relationships')
    op.drop_index(op.f('ix_emotion_relationships_analysis_id'), table_name='emotion_relationships')
    op.create_index('idx_emotion_rel_type', 'emotion_relationships', ['relationship_type'], unique=False)
    op.create_index('idx_emotion_rel_analysis', 'emotion_relationships', ['analysis_id'], unique=False)
    op.alter_column('emotion_relationships', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('emotion_relationships', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'emotion_goals',
        'User-defined emotion goals for transition pathfinding',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'emotion_goals', type_='foreignkey')
    op.create_foreign_key('emotion_goals_goal_emotion_id_fkey', 'emotion_goals', 'atlas_definitions', ['goal_emotion_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_emotion_goals_user_id'), table_name='emotion_goals')
    op.drop_index(op.f('ix_emotion_goals_status'), table_name='emotion_goals')
    op.drop_index(op.f('ix_emotion_goals_session_id'), table_name='emotion_goals')
    op.create_index('idx_emotion_goals_user', 'emotion_goals', ['user_id'], unique=False)
    op.create_index('idx_emotion_goals_status', 'emotion_goals', ['status'], unique=False)
    op.create_index('idx_emotion_goals_session', 'emotion_goals', ['session_id'], unique=False)
    op.alter_column('emotion_goals', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('emotion_goals', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('emotion_goals', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               nullable=True)
    op.alter_column('emotion_goals', 'target_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('emotion_goals', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('emotion_goals', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'detected_emotions',
        'Individual emotions (1-3) detected in multi-emotion analysis',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'detected_emotions', type_='foreignkey')
    op.create_foreign_key('detected_emotions_emotion_id_fkey', 'detected_emotions', 'atlas_definitions', ['emotion_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_detected_emotions_prominence'), table_name='detected_emotions')
    op.drop_index(op.f('ix_detected_emotions_emotion_id'), table_name='detected_emotions')
    op.drop_index(op.f('ix_detected_emotions_analysis_id'), table_name='detected_emotions')
    op.create_index('idx_detected_emotions_prominence', 'detected_emotions', ['prominence'], unique=False)
    op.create_index('idx_detected_emotions_emotion', 'detected_emotions', ['emotion_id'], unique=False)
    op.create_index('idx_detected_emotions_analysis', 'detected_emotions', ['analysis_id'], unique=False)
    op.alter_column('detected_emotions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('detected_emotions', 'emotion_id',
               existing_type=sa.UUID(),
               comment='Foreign key with CASCADE to allow atlas re-seeding',
               existing_nullable=True)
    op.alter_column('detected_emotions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('clinical_alerts', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'clinical_alerts',
        'Stores clinical alert evaluations for emotional analysis sessions with audit trail',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'clinical_alerts', type_='foreignkey')
    op.create_foreign_key('clinical_alerts_session_id_fkey', 'clinical_alerts', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_clinical_alerts_type'), table_name='clinical_alerts')
    op.drop_index(op.f('ix_clinical_alerts_timestamp'), table_name='clinical_alerts')
    op.drop_index(op.f('ix_clinical_alerts_session_id'), table_name='clinical_alerts')
    op.drop_index(op.f('ix_clinical_alerts_level'), table_name='clinical_alerts')
    op.create_index('idx_clinical_alerts_type', 'clinical_alerts', ['type'], unique=False)
    op.create_index('idx_clinical_alerts_timestamp', 'clinical_alerts', ['timestamp'], unique=False)
    op.create_index('idx_clinical_alerts_session', 'clinical_alerts', ['session_id'], unique=False)
    op.create_index('idx_clinical_alerts_level', 'clinical_alerts', ['level'], unique=False)
    op.alter_column('clinical_alerts', 'version',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'1.0'::character varying"),
               comment='Alert rule version for tracking threshold changes over time',
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'threshold_used',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Clinical thresholds applied for this alert evaluation',
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'triggered_by',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='VAC and prosody values that triggered the alert',
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'suggestion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('clinical_alerts', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('high_arousal', 'voice_mismatch', 'low_confidence', 'pattern_concern', 'voice_quality', name='alert_type'),
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'level',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('critical', 'warning', 'attention', 'stable', name='alert_level'),
               existing_nullable=False)
    op.alter_column('clinical_alerts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'chat_sessions',
        'Chat sessions for emotional analysis chat interface',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_started_at'), table_name='chat_sessions')
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('idx_chat_sessions_started_at', 'chat_sessions', [sa.text('started_at DESC')], unique=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_sessions', 'deep_feeling_mode',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'tone_preference',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'warm'::character varying"),
               nullable=True)
    op.alter_column('chat_sessions', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'chat_messages',
        'Individual messages within chat sessions with analysis data',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_emotion_id_fkey', 'chat_messages', 'atlas_definitions', ['emotion_id'], ['id'])
    op.drop_index(op.f('ix_chat_messages_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_emotion_id'), table_name='chat_messages')
    op.create_index('ix_chat_messages_semantic_embedding', 'chat_messages', ['semantic_embedding'], unique=False, postgresql_ops={'semantic_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_chat_messages_timestamp', 'chat_messages', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('idx_chat_messages_emotion_id', 'chat_messages', ['emotion_id'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_messages', 'insights',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='AI-generated insights combining voice and content analysis',
               existing_nullable=True)
    op.alter_column('chat_messages', 'prosody_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSONB storage for detailed voice features (jitter, shimmer, HNR, etc.)',
               existing_nullable=True)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table_comment(
        'category_transitions',
        'Difficulty matrix for category-to-category emotional transitions',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_category_trans_to', 'category_transitions', ['to_category'], unique=False)
    op.create_index('idx_category_trans_from', 'category_transitions', ['from_category'], unique=False)
    op.create_index('idx_category_trans_difficulty', 'category_transitions', ['difficulty_score'], unique=False)
    op.create_unique_constraint('category_transitions_from_category_to_category_key', 'category_transitions', ['from_category', 'to_category'], postgresql_nulls_not_distinct=False)
    op.alter_column('category_transitions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('category_transitions', 'requires_bridge',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('category_transitions', 'is_prohibited',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('category_transitions', 'difficulty_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Scale 0-1 where 1.0 = impossible without bridge',
               existing_nullable=False)
    op.alter_column('category_transitions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('atlas_definitions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('emotion_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('definition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vac_vector', pgvector.sqlalchemy.vector.VECTOR(dim=3), autoincrement=False, nullable=False),
    sa.Column('q_constant', pgvector.sqlalchemy.vector.VECTOR(dim=4), autoincrement=False, nullable=False),
    sa.Column('semantic_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=False),
    sa.Column('haptic_pattern_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('color_hint', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='atlas_definitions_pkey')
    )
    op.create_index('ix_atlas_definitions_emotion_name', 'atlas_definitions', ['emotion_name'], unique=True)
    op.create_index('ix_atlas_definitions_category', 'atlas_definitions', ['category'], unique=False)
    op.drop_index(op.f('ix_emotion_definitions_emotion_name'), table_name='emotion_definitions')
    op.drop_index(op.f('ix_emotion_definitions_collection_id'), table_name='emotion_definitions')
    op.drop_index(op.f('ix_emotion_definitions_category'), table_name='emotion_definitions')
    op.drop_table('emotion_definitions')
    op.drop_index(op.f('ix_emotion_collections_name'), table_name='emotion_collections')
    op.drop_table('emotion_collections')
    # ### end Alembic commands ###
