"""add_message_relationships

Revision ID: 2ae04862ad3f
Revises: 357748608b36
Create Date: 2026-01-19 21:44:53.520742

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ae04862ad3f"
down_revision: Union[str, None] = "357748608b36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_relationships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_message_id", sa.Uuid(), nullable=False),
        sa.Column("target_message_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=50), nullable=False),
        sa.Column(
            "relationship_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"], ["chat_messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_message_id"], ["chat_messages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_relationships_relationship_type"),
        "message_relationships",
        ["relationship_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_relationships_source_message_id"),
        "message_relationships",
        ["source_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_relationships_target_message_id"),
        "message_relationships",
        ["target_message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_message_relationships_target_message_id"),
        table_name="message_relationships",
    )
    op.drop_index(
        op.f("ix_message_relationships_source_message_id"),
        table_name="message_relationships",
    )
    op.drop_index(
        op.f("ix_message_relationships_relationship_type"),
        table_name="message_relationships",
    )
    op.drop_table("message_relationships")
    # ### end Alembic commands ###
