---
- name: Install Fail2Ban (EPEL required)
  dnf:
    name: fail2ban
    state: present

- name: Configure Fail2Ban (jail.local)
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: Restart Fail2Ban

- name: Enable and start Fail2Ban
  service:
    name: fail2ban
    state: started
    enabled: yes
