---
- name: Install Python 3.12
  dnf:
    name:
      - python3.12
      - python3.12-devel
      - python3.12-pip
    state: present
    nobest: true
    skip_broken: true

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    executable: pip3.12

- name: Install Node.js 20 Repo
  shell: curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
  args:
    creates: /etc/yum.repos.d/nodesource-nodejs.repo

- name: Install Node.js
  dnf:
    name: nodejs
    state: present
    nobest: true
    skip_broken: true
